services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    PiWeb\PiBreadcrumb\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Event,Migrations,Tests,Kernel.php}'
